---
- name: Import dependency role container-engine/validate-container-engine
  import_role:
    name: container-engine/validate-container-engine
  tags:
    - container-engine
    - validate-container-engine

- name: Include dependency role container-engine/kata-containers
  include_role:
    name: container-engine/kata-containers
  when:
    - kata_containers_enabled
  tags:
    - container-engine
    - kata-containers

- name: Include dependency role container-engine/gvisor
  include_role:
    name: container-engine/gvisor
  when:
    - gvisor_enabled
    - container_manager in ['docker', 'containerd']
  tags:
    - container-engine
    - gvisor

- name: Include dependency role container-engine/crun
  include_role:
    name: container-engine/crun
  when:
    - crun_enabled
  tags:
    - container-engine
    - crun

- name: Include dependency role container-engine/youki
  include_role:
    name: container-engine/youki
  when:
    - youki_enabled
    - container_manager == 'crio'
  tags:
    - container-engine
    - youki

- name: Include dependency role container-engine/cri-o
  include_role:
    name: container-engine/cri-o
  when:
    - container_manager == 'crio'
  tags:
    - container-engine
    - crio

- name: Include dependency role container-engine/containerd
  include_role:
    name: container-engine/containerd
  when:
    - container_manager == 'containerd'
  tags:
    - container-engine
    - containerd

- name: Include dependency role container-engine/containerd
  include_role:
    name: container-engine/containerd
  when:
    - container_manager == 'docker'
  tags:
    - container-engine
    - docker
