---
- name: Import dependency role network_plugin/cni
  import_role:
    name: network_plugin/cni

- name: Include dependency role network_plugin/cilium
  include_role:
    name: network_plugin/cilium
  when: kube_network_plugin == 'cilium' or cilium_deploy_additionally | default(false) | bool
  tags:
    - cilium

- name: Include dependency role network_plugin/calico
  include_role:
    name: network_plugin/calico
  when: kube_network_plugin == 'calico'
  tags:
    - calico

- name: Include dependency role network_plugin/flannel
  include_role:
    name: network_plugin/flannel
  when: kube_network_plugin == 'flannel'
  tags:
    - flannel

- name: Include dependency role network_plugin/weave
  include_role:
    name: network_plugin/weave
  when: kube_network_plugin == 'weave'
  tags:
    - weave

- name: Include dependency role network_plugin/macvlan
  include_role:
    name: network_plugin/macvlan
  when: kube_network_plugin == 'macvlan'
  tags:
    - macvlan

- name: Include dependency role network_plugin/kube-ovn
  include_role:
    name: network_plugin/kube-ovn
  when: kube_network_plugin == 'kube-ovn'
  tags:
    - kube-ovn

- name: Include dependency role network_plugin/kube-router
  include_role:
    name: network_plugin/kube-router
  when: kube_network_plugin == 'kube-router'
  tags:
    - kube-router

- name: Include dependency role network_plugin/custom_cni
  include_role:
    name: network_plugin/custom_cni
  when: kube_network_plugin == 'custom_cni'
  tags:
    - custom_cni

- name: Include dependency role network_plugin/multus
  include_role:
    name: network_plugin/multus
  when: kube_network_plugin_multus
  tags:
    - multus
